added jekyll path

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -63,4 +63,8 @@ jobs:
           git add -A
           git commit -m "Deploy preview for ${GITHUB_REF_NAME}"
           git push origin gh-pages
+        else
+         echo "Error: _site directory not found"
+      exit 1
+    fi
       
